### ISSUE TITLE
Use labels instead of legend

### ISSUE THREAD

**Issue by sen1** [dmevers-gh/intro-data-capstone-musclehub#1]
https://github.com/dmevers-gh/intro-data-capstone-musclehub/blob/a63fd49efc14fb85730a9a3312431093e076dfc1/MuscleHub/musclehub.py#L189-L192

A minor point here. `legend` will set the legend at some corner of the text. `labels` will label each slices of the pie. Thats why I would use the `labels` instead of `legend`.
```
plt.pie(ab_counts.first_name.values, labels=['A', 'B'], autopct='%0.2f%%')
```

**Comment by dmevers-gh** [comment]
I prefer a legend when there are a smaller number of items to track. Labels become unreadable at some point and always stick them where the high-values are displayed, which can be a distraction.

It is also easier to "photoshop out" a legend vs a label.

That was my thinking.
