### ISSUE TITLE
Add line breaks to increase code readability

### ISSUE THREAD

**Issue by sen1** [dmevers-gh/intro-data-capstone-musclehub#2]
https://github.com/dmevers-gh/intro-data-capstone-musclehub/blob/a63fd49efc14fb85730a9a3312431093e076dfc1/MuscleHub/musclehub.py#L233

Again a minor point here. I would add line breaks to increase code readability. Code styling is not something we followed in this course. However, it is very important.
```
app_pivot = app_counts.pivot(columns='is_application',
                            index='ab_test_group',
                            values='first_name')\
            .reset_index()
```

Read the PEP8 guide for the maximum length of a code line:
https://www.python.org/dev/peps/pep-0008/#maximum-line-length

**Comment by dmevers-gh** [comment]
I was starting to get frustrated with what was happening with the line breaks getting moved up. Jupyter is not my favorite notebook (I prefer Zeppelin) and copy/paste was causing issues.

So I prototyped it all as one line and forgot to go back and clean it up.

You are correct, line breaks make all the difference.
