### ISSUE TITLE
Assign to variable

### ISSUE THREAD

**Issue by sen1** [dmevers-gh/intro-data-capstone-musclehub#3]
https://github.com/dmevers-gh/intro-data-capstone-musclehub/blob/a63fd49efc14fb85730a9a3312431093e076dfc1/MuscleHub/musclehub.py#L368

Assign to a variable. The pvalue is the second output. It is not trivial to understand for a reader.
```
 _, pvalue, _, _ = chi2_contingency(contingency) 
```

`_` is a special character in python to ignore values you dont want. Read more here if you dont know.
https://hackernoon.com/understanding-the-underscore-of-python-309d1a029edc

**Comment by dmevers-gh** [comment]
Understood.
